/**
 * ================================================
 * LibLoader : a free Java resource loading library
 * ================================================
 *
 * Project Info:  http://jfreereport.pentaho.org/libloader/
 *
 * (C) Copyright 2006, by Pentaho Corporation and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * [Java is a trademark or registered trademark of Sun Microsystems, Inc.
 * in the United States and other countries.]
 *
 *
 * ------------
 * $Id$
 * ------------
 * (C) Copyright 2006, by Pentaho Corporation.
 */

package org.jfree.resourceloader;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Collections;

/**
 * Creation-Date: 16.05.2006, 15:26:32
 *
 * @author Thomas Morgner
 */
public abstract class AbstractResourceKey implements ResourceKey
{
  private Map parameters;
  private Integer hashCode;

  public AbstractResourceKey(final Map parameters)
  {
    this.parameters = new HashMap();
    final Iterator entries = parameters.entrySet().iterator();
    while (entries.hasNext())
    {
      Map.Entry entry = (Map.Entry) entries.next();
      final Object key = entry.getKey();
      final Object value = entry.getValue();
      if (value instanceof Serializable == false)
      {
        throw new IllegalArgumentException(
                "Value for key " + key + " is not serializable: " + value);
      }
      if (key instanceof LoaderParameterKey)
      {
        this.parameters.put(key, value);
      }
      else if (key instanceof FactoryParameterKey)
      {
        this.parameters.put(key, value);
      }
    }
  }

  public Object getLoaderParameter(LoaderParameterKey key)
  {
    return parameters.get(key);
  }

  public Object getFactoryParameter(FactoryParameterKey key)
  {
    return parameters.get(key);
  }

  /**
   * Creates a unique identifier for this key.
   * <p/>
   * The following statement must be true for all external forms generated by
   * this method: (key1.equals(key2) == key1.toExternalForm().equals(key2.toExternalForm())
   *
   * @return
   */
  public String toExternalForm()
  {
    return null;
  }

  public Map getParameters ()
  {
    return Collections.unmodifiableMap(parameters);
  }

  public boolean equals(final Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o instanceof AbstractResourceKey == false)
    {
      return false;
    }

    final AbstractResourceKey that = (AbstractResourceKey) o;

    if (!parameters.equals(that.parameters))
    {
      return false;
    }

    return true;
  }

  public int hashCode()
  {
    if (hashCode == null)
    {
      hashCode = new Integer(parameters.hashCode ());
    }
    return hashCode.intValue();
  }
}
