package com.jrefinery.report.ext.junit;

/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id: TestAll.java,v 1.5 2003/03/26 22:52:43 taqua Exp $
 * $Author: taqua $
 * $Date: 2003/03/26 22:52:43 $
 */

import junit.framework.Test;
import junit.framework.TestSuite;

/**
 * TestSuite that runs all the tests.
 * You can run unit tests in many ways, however this file is designed
 * performing tests in the following way:<br/>
 * <pre>
 *   java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 * </pre>
 *
 */
public class TestAll
{

  public static void main(String[] args)
  {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[ args)

  public static Test suite()
  {
    TestSuite suite = new TestSuite("All JUnit Tests");
    return suite;
  } // end of suite()
} // end of com.jrefinery.report.ext.junit.TestAll


