/**
 * ================================================
 * LibLoader : a free Java resource loading library
 * ================================================
 *
 * Project Info:  http://www.jfree.org/jfreereport/libloader/
 * Project Lead:  Thomas Morgner;
 *
 * (C) Copyright 2006, by Pentaho Corporation and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * [Java is a trademark or registered trademark of Sun Microsystems, Inc.
 * in the United States and other countries.]
 *
 * ------------
 * ClassloaderResourceKey.java
 * ------------
 * (C) Copyright 2006, by Pentaho Corporation.
 *
 * Original Author:  Thomas Morgner;
 * Contributor(s):   -;
 *
 * $Id: ClassloaderResourceKey.java,v 1.2 2006/04/29 15:07:39 taqua Exp $
 *
 * Changes
 * -------
 *
 *
 */
package org.jfree.resourceloader.loader.resource;

import java.util.Map;

import org.jfree.resourceloader.AbstractResourceKey;

/**
 * This resource key describes a loadable system resource, independent of the
 * actual classpath used.
 *
 * @author Thomas Morgner
 */
public class ClassloaderResourceKey extends AbstractResourceKey
{
  private transient String resource;

  public ClassloaderResourceKey(final Map values)
  {
    super(values);
    final String valueString = (String) getLoaderParameter(AbstractResourceKey.CONTENT_KEY);
    if (valueString == null)
    {
      throw new NullPointerException();
    }
    if (valueString.startsWith("res://") == false)
    {
      throw new IllegalArgumentException(valueString);
    }
    this.resource = valueString;
  }

  /**
   * Returns the schema of this resource key. The schema can be mapped to a
   * known resource loader. If no resource loader is available for the given
   * schema, the resource will be unavailable.
   *
   * @return
   */
  public String getSchema()
  {
    return "res";
  }

  public String getResource()
  {
    if (resource == null)
    {
      resource = (String) getLoaderParameter(AbstractResourceKey.CONTENT_KEY);
    }
    return resource;
  }

  public String getResourcePath()
  {
    return getResource().substring(6);
  }

  /**
   * Creates a unique identifier for this key.
   * <p/>
   * The following statement must be true for all external forms generated by
   * this method: (key1.equals(key2) == key1.toExternalForm().equals(key2.toExternalForm())
   *
   * @return
   */
  public String toExternalForm()
  {
    return getResource();
  }

  public String toString()
  {
    return "ClassLoaderResourceKey={resource=" + resource + "}";
  }
}
