/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id:$
 * $Author:$
 * $Date:$
 */
package com.jrefinery.report.ext.junit.base.preview;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.preview.PreviewFrame;

/**
 * File <code>PreviewFrameTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.preview.PreviewFrameTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class PreviewFrameTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected PreviewFrame varPreviewFrame;

  /**
   * Public constructor for creating testing class.
   */
  public PreviewFrameTestCase(String name) {
    super(name);
  } // end of PreviewFrameTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    // Initialize your variable(s) here
    // for example:
    // varPreviewFrame = new PreviewFrame(...);
    // But note that there is no default constructor in PreviewFrame
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(PreviewFrameTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.preview.ReportPane access$000( ... )
   * from tested class
   */
  public void testAccess$0001507199688() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAccess$0001507199688( ... )

  /**
   * Method for testing how works original method:
   * void actionPerformed(java.awt.event.ActionEvent)
   * from tested class
   */
  public void testActionPerformed1002842412() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testActionPerformed1002842412(java.awt.event.ActionEvent)

  /**
   * Method for testing how works original method:
   * void attemptPageSetup()
   * from tested class
   */
  public void testAttemptPageSetup() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAttemptPageSetup()

  /**
   * Method for testing how works original method:
   * void attemptPrint()
   * from tested class
   */
  public void testAttemptPrint() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAttemptPrint()

  /**
   * Method for testing how works original method:
   * void attemptSaveAs()
   * from tested class
   */
  public void testAttemptSaveAs() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAttemptSaveAs()

  /**
   * Method for testing how works original method:
   * javax.swing.JButton createButton(javax.swing.Action)
   * from tested class
   */
  public void testCreateButton164989854() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateButton164989854(javax.swing.Action)

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultAboutAction()
   * from tested class
   */
  public void testCreateDefaultAboutAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultAboutAction()

  /**
   * Method for testing how works original method:
   * void createDefaultActions()
   * from tested class
   */
  public void testCreateDefaultActions() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultActions()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultCloseAction()
   * from tested class
   */
  public void testCreateDefaultCloseAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultCloseAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultFirstPageAction()
   * from tested class
   */
  public void testCreateDefaultFirstPageAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultFirstPageAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultGotoAction()
   * from tested class
   */
  public void testCreateDefaultGotoAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultGotoAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultLastPageAction()
   * from tested class
   */
  public void testCreateDefaultLastPageAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultLastPageAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultNextPageAction()
   * from tested class
   */
  public void testCreateDefaultNextPageAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultNextPageAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultPageSetupAction()
   * from tested class
   */
  public void testCreateDefaultPageSetupAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultPageSetupAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultPreviousPageAction()
   * from tested class
   */
  public void testCreateDefaultPreviousPageAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultPreviousPageAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultPrintAction()
   * from tested class
   */
  public void testCreateDefaultPrintAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultPrintAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultSaveAsAction()
   * from tested class
   */
  public void testCreateDefaultSaveAsAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultSaveAsAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultZoomInAction()
   * from tested class
   */
  public void testCreateDefaultZoomInAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultZoomInAction()

  /**
   * Method for testing how works original method:
   * javax.swing.Action createDefaultZoomOutAction()
   * from tested class
   */
  public void testCreateDefaultZoomOutAction() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultZoomOutAction()

  /**
   * Method for testing how works original method:
   * javax.swing.JMenuBar createMenuBar(java.util.ResourceBundle)
   * from tested class
   */
  public void testCreateMenuBar156985360() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateMenuBar156985360(java.util.ResourceBundle)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.preview.ReportPane createReportPane(com.jrefinery.report.JFreeReport)
   * from tested class
   */
  public void testCreateReportPane972083635() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateReportPane972083635(com.jrefinery.report.JFreeReport)

  /**
   * Method for testing how works original method:
   * javax.swing.JPanel createStatusBar()
   * from tested class
   */
  public void testCreateStatusBar() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateStatusBar()

  /**
   * Method for testing how works original method:
   * javax.swing.JToolBar createToolBar()
   * from tested class
   */
  public void testCreateToolBar() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateToolBar()

  /**
   * Method for testing how works original method:
   * void decreasePageNumber()
   * from tested class
   */
  public void testDecreasePageNumber() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testDecreasePageNumber()

  /**
   * Method for testing how works original method:
   * void decreaseZoom()
   * from tested class
   */
  public void testDecreaseZoom() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testDecreaseZoom()

  /**
   * Method for testing how works original method:
   * void dispose()
   * from tested class
   */
  public void testDispose() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testDispose()

  /**
   * Method for testing how works original method:
   * void firstPage()
   * from tested class
   */
  public void testFirstPage() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testFirstPage()

  /**
   * Method for testing how works original method:
   * java.util.ResourceBundle getResources()
   * from tested class
   */
  public void testGetResources() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetResources()

  /**
   * Method for testing how works original method:
   * javax.swing.JLabel getStatus()
   * from tested class
   */
  public void testGetStatus() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetStatus()

  /**
   * Method for testing how works original method:
   * double getZoomFactor()
   * from tested class
   */
  public void testGetZoomFactor() {

/* No default constructor, code commented out...
    // Warning return type of 'get' method is not compatible with
    // corresponding 'set' method parameter.
*/
    assertTrue("Warning! This new test method with no real test code inside.", false);
/* No default constructor, code commented out...
    // Warning return type of 'get' method is not compatible with
    // corresponding 'set' method parameter.
*/

  } // end of testGetZoomFactor()

  /**
   * Method for testing how works original method:
   * void increasePageNumber()
   * from tested class
   */
  public void testIncreasePageNumber() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIncreasePageNumber()

  /**
   * Method for testing how works original method:
   * void increaseZoom()
   * from tested class
   */
  public void testIncreaseZoom() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIncreaseZoom()

  /**
   * Method for testing how works original method:
   * boolean isLargeIconsEnabled()
   * from tested class
   */
  public void testIsLargeIconsEnabled() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIsLargeIconsEnabled()

  /**
   * Method for testing how works original method:
   * boolean isToolbarFloatable()
   * from tested class
   */
  public void testIsToolbarFloatable() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIsToolbarFloatable()

  /**
   * Method for testing how works original method:
   * void lastPage()
   * from tested class
   */
  public void testLastPage() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testLastPage()

  /**
   * Method for testing how works original method:
   * void processWindowEvent(java.awt.event.WindowEvent)
   * from tested class
   */
  public void testProcessWindowEvent671810214() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testProcessWindowEvent671810214(java.awt.event.WindowEvent)

  /**
   * Method for testing how works original method:
   * void propertyChange(java.beans.PropertyChangeEvent)
   * from tested class
   */
  public void testPropertyChange1791001374() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testPropertyChange1791001374(java.beans.PropertyChangeEvent)

  /**
   * Method for testing how works original method:
   * void registerAction(javax.swing.Action)
   * from tested class
   */
  public void testRegisterAction164989854() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRegisterAction164989854(javax.swing.Action)

  /**
   * Method for testing how works original method:
   * void registerDefaultActions()
   * from tested class
   */
  public void testRegisterDefaultActions() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRegisterDefaultActions()

  /**
   * Method for testing how works original method:
   * void setLargeIconsEnabled(boolean)
   * from tested class
   */
  public void testSetLargeIconsEnabled64711720() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSetLargeIconsEnabled64711720(boolean)

  /**
   * Method for testing how works original method:
   * void setToolbarFloatable(boolean)
   * from tested class
   */
  public void testSetToolbarFloatable64711720() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSetToolbarFloatable64711720(boolean)

  /**
   * Method for testing how works original method:
   * void setZoomFactor(int)
   * from tested class
   */
  public void testSetZoomFactor104431() {

/* No default constructor, code commented out...
    // Warning return type of 'get' method is not compatible with
    // corresponding 'set' method parameter.
*/
    assertTrue("Warning! This new test method with no real test code inside.", false);
/* No default constructor, code commented out...
    // Warning return type of 'get' method is not compatible with
    // corresponding 'set' method parameter.
*/

  } // end of testSetZoomFactor104431(int)

  /**
   * Method for testing how works original method:
   * void validate()
   * from tested class
   */
  public void testValidate() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testValidate()

} // end of PreviewFrameTestCase
