/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id:$
 * $Author:$
 * $Date:$
 */
package com.jrefinery.report.ext.junit.base.util;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.util.ExceptionDialog;

/**
 * File <code>ExceptionDialogTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.util.ExceptionDialogTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class ExceptionDialogTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected ExceptionDialog varExceptionDialog;

  /**
   * Public constructor for creating testing class.
   */
  public ExceptionDialogTestCase(String name) {
    super(name);
  } // end of ExceptionDialogTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
        public void eventDispatched(AWTEvent event) {
          WindowEvent we = ((WindowEvent) event);
          if (we.getID() == WindowEvent.WINDOW_OPENED)
            we.getWindow().dispose();
        }
      }, AWTEvent.WINDOW_EVENT_MASK);
    varExceptionDialog = new ExceptionDialog();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(ExceptionDialogTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * javax.swing.JScrollPane access$000( ... )
   * from tested class
   */
  public void testAccess$0001463395288() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAccess$0001463395288( ... )

  /**
   * Method for testing how works original method:
   * void adjustSize()
   * from tested class
   */
  public void testAdjustSize() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAdjustSize()

  /**
   * Method for testing how works original method:
   * java.lang.Exception getException()
   * from tested class
   */
  public void testGetException() {

    varExceptionDialog.setException((Exception)null);
    assertEquals((Exception)null, varExceptionDialog.getException());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varExceptionDialog.setException((Exception)null);
    assertEquals((Exception)null, varExceptionDialog.getException());

  } // end of testGetException()

  /**
   * Method for testing how works original method:
   * java.lang.String getMessage()
   * from tested class
   */
  public void testGetMessage() {

    varExceptionDialog.setMessage((String)null);
    assertEquals((String)null, varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"");
    assertEquals((String)"", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\u0000");
    assertEquals((String)"\u0000", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)" ");
    assertEquals((String)" ", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\n");
    assertEquals((String)"\n", varExceptionDialog.getMessage());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varExceptionDialog.setMessage((String)null);
    assertEquals((String)null, varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"");
    assertEquals((String)"", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\u0000");
    assertEquals((String)"\u0000", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)" ");
    assertEquals((String)" ", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\n");
    assertEquals((String)"\n", varExceptionDialog.getMessage());

  } // end of testGetMessage()

  /**
   * Method for testing how works original method:
   * void setException(java.lang.Exception)
   * from tested class
   */
  public void testSetException72706427() {

    varExceptionDialog.setException((Exception)null);
    assertEquals((Exception)null, varExceptionDialog.getException());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varExceptionDialog.setException((Exception)null);
    assertEquals((Exception)null, varExceptionDialog.getException());

  } // end of testSetException72706427(java.lang.Exception)

  /**
   * Method for testing how works original method:
   * void setMessage(java.lang.String)
   * from tested class
   */
  public void testSetMessage1195259493() {

    varExceptionDialog.setMessage((String)null);
    assertEquals((String)null, varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"");
    assertEquals((String)"", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\u0000");
    assertEquals((String)"\u0000", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)" ");
    assertEquals((String)" ", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\n");
    assertEquals((String)"\n", varExceptionDialog.getMessage());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varExceptionDialog.setMessage((String)null);
    assertEquals((String)null, varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"");
    assertEquals((String)"", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\u0000");
    assertEquals((String)"\u0000", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)" ");
    assertEquals((String)" ", varExceptionDialog.getMessage());
    varExceptionDialog.setMessage((String)"\n");
    assertEquals((String)"\n", varExceptionDialog.getMessage());

  } // end of testSetMessage1195259493(java.lang.String)

  /**
   * Method for testing how works original method:
   * void showExceptionDialog( ... )
   * from tested class
   */
  public void testShowExceptionDialog1195259493119525949372706427() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testShowExceptionDialog1195259493119525949372706427( ... )

} // end of ExceptionDialogTestCase
