/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id:$
 * $Author:$
 * $Date:$
 */
package com.jrefinery.report.ext.junit.base.util;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.util.ReadOnlyList;

/**
 * File <code>ReadOnlyListTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.util.ReadOnlyListTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class ReadOnlyListTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected ReadOnlyList varReadOnlyList;

  /**
   * Public constructor for creating testing class.
   */
  public ReadOnlyListTestCase(String name) {
    super(name);
  } // end of ReadOnlyListTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    // Initialize your variable(s) here
    // for example:
    // varReadOnlyList = new ReadOnlyList(...);
    // But note that there is no default constructor in ReadOnlyList
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(ReadOnlyListTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * void add(int, java.lang.Object)
   * from tested class
   */
  public void testAdd1044311063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAdd1044311063877011(int, java.lang.Object)

  /**
   * Method for testing how works original method:
   * boolean add(java.lang.Object)
   * from tested class
   */
  public void testAdd1063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAdd1063877011(java.lang.Object)

  /**
   * Method for testing how works original method:
   * boolean addAll(java.util.Collection)
   * from tested class
   */
  public void testAddAll688322466() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAddAll688322466(java.util.Collection)

  /**
   * Method for testing how works original method:
   * boolean addAll(int, java.util.Collection)
   * from tested class
   */
  public void testAddAll104431688322466() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAddAll104431688322466(int, java.util.Collection)

  /**
   * Method for testing how works original method:
   * void clear()
   * from tested class
   */
  public void testClear() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testClear()

  /**
   * Method for testing how works original method:
   * boolean contains(java.lang.Object)
   * from tested class
   */
  public void testContains1063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testContains1063877011(java.lang.Object)

  /**
   * Method for testing how works original method:
   * boolean containsAll(java.util.Collection)
   * from tested class
   */
  public void testContainsAll688322466() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testContainsAll688322466(java.util.Collection)

  /**
   * Method for testing how works original method:
   * java.lang.Object get(int)
   * from tested class
   */
  public void testGet104431() {

/* No default constructor, code commented out...
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

*/
    assertTrue("Warning! This new test method with no real test code inside.", false);
/* No default constructor, code commented out...
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

*/

  } // end of testGet104431(int)

  /**
   * Method for testing how works original method:
   * int indexOf(java.lang.Object)
   * from tested class
   */
  public void testIndexOf1063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIndexOf1063877011(java.lang.Object)

  /**
   * Method for testing how works original method:
   * boolean isEmpty()
   * from tested class
   */
  public void testIsEmpty() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIsEmpty()

  /**
   * Method for testing how works original method:
   * java.util.Iterator iterator()
   * from tested class
   */
  public void testIterator() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIterator()

  /**
   * Method for testing how works original method:
   * int lastIndexOf(java.lang.Object)
   * from tested class
   */
  public void testLastIndexOf1063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testLastIndexOf1063877011(java.lang.Object)

  /**
   * Method for testing how works original method:
   * java.util.ListIterator listIterator(int)
   * from tested class
   */
  public void testListIterator104431() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testListIterator104431(int)

  /**
   * Method for testing how works original method:
   * java.util.ListIterator listIterator()
   * from tested class
   */
  public void testListIterator() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testListIterator()

  /**
   * Method for testing how works original method:
   * java.lang.Object remove(int)
   * from tested class
   */
  public void testRemove104431() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRemove104431(int)

  /**
   * Method for testing how works original method:
   * boolean remove(java.lang.Object)
   * from tested class
   */
  public void testRemove1063877011() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRemove1063877011(java.lang.Object)

  /**
   * Method for testing how works original method:
   * boolean removeAll(java.util.Collection)
   * from tested class
   */
  public void testRemoveAll688322466() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRemoveAll688322466(java.util.Collection)

  /**
   * Method for testing how works original method:
   * boolean retainAll(java.util.Collection)
   * from tested class
   */
  public void testRetainAll688322466() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRetainAll688322466(java.util.Collection)

  /**
   * Method for testing how works original method:
   * java.lang.Object set(int, java.lang.Object)
   * from tested class
   */
  public void testSet1044311063877011() {

/* No default constructor, code commented out...
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

*/
    assertTrue("Warning! This new test method with no real test code inside.", false);
/* No default constructor, code commented out...
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

*/

  } // end of testSet1044311063877011(int, java.lang.Object)

  /**
   * Method for testing how works original method:
   * int size()
   * from tested class
   */
  public void testSize() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSize()

  /**
   * Method for testing how works original method:
   * java.util.List subList(int, int)
   * from tested class
   */
  public void testSubList104431104431() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSubList104431104431(int, int)

  /**
   * Method for testing how works original method:
   * java.lang.Object[] toArray()
   * from tested class
   */
  public void testToArray() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testToArray()

  /**
   * Method for testing how works original method:
   * java.lang.Object[] toArray(java.lang.Object[])
   * from tested class
   */
  public void testToArray183594037() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testToArray183594037(java.lang.Object[])

} // end of ReadOnlyListTestCase
