/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id: ReportGeneratorTestCase.java,v 1.1 2002/07/08 22:10:38 taqua Exp $
 * $Author: taqua $
 * $Date: 2002/07/08 22:10:38 $
 */
package com.jrefinery.report.ext.junit.base.io;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.io.ReportGenerator;

/**
 * File <code>ReportGeneratorTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.io.ReportGeneratorTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class ReportGeneratorTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected ReportGenerator varReportGenerator;

  /**
   * Public constructor for creating testing class.
   */
  public ReportGeneratorTestCase(String name) {
    super(name);
  } // end of ReportGeneratorTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    varReportGenerator = ReportGenerator.getInstance();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(ReportGeneratorTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.io.AbstractReportDefinitionHandler createDefaultHandler(java.net.URL)
   * from tested class
   */
  public void testCreateDefaultHandler2050244018() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testCreateDefaultHandler2050244018(java.net.URL)

  /**
   * Method for testing how works original method:
   * java.lang.String getDTDLocation()
   * from tested class
   */
  public void testGetDTDLocation() {

    varReportGenerator.setDTDLocation((String)null);
    assertEquals((String)null, varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"");
    assertEquals((String)"", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\u0000");
    assertEquals((String)"\u0000", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)" ");
    assertEquals((String)" ", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\n");
    assertEquals((String)"\n", varReportGenerator.getDTDLocation());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varReportGenerator.setDTDLocation((String)null);
    assertEquals((String)null, varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"");
    assertEquals((String)"", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\u0000");
    assertEquals((String)"\u0000", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)" ");
    assertEquals((String)" ", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\n");
    assertEquals((String)"\n", varReportGenerator.getDTDLocation());

  } // end of testGetDTDLocation()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.io.AbstractReportDefinitionHandler getDefaultHandler()
   * from tested class
   */
  public void testGetDefaultHandler() {

    varReportGenerator.setDefaultHandler((com.jrefinery.report.io.AbstractReportDefinitionHandler)null);
    assertEquals((com.jrefinery.report.io.AbstractReportDefinitionHandler)null, varReportGenerator.getDefaultHandler());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varReportGenerator.setDefaultHandler((com.jrefinery.report.io.AbstractReportDefinitionHandler)null);
    assertEquals((com.jrefinery.report.io.AbstractReportDefinitionHandler)null, varReportGenerator.getDefaultHandler());

  } // end of testGetDefaultHandler()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.io.ReportGenerator getInstance()
   * from tested class
   */
  public void testGetInstance() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetInstance()

  /**
   * Method for testing how works original method:
   * javax.xml.parsers.SAXParser getParser()
   * from tested class
   */
  public void testGetParser() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetParser()

  /**
   * Method for testing how works original method:
   * void initFromSystem()
   * from tested class
   */
  public void testInitFromSystem() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testInitFromSystem()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.JFreeReport parseReport(java.net.URL, java.net.URL)
   * from tested class
   */
  public void testParseReport20502440182050244018() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testParseReport20502440182050244018(java.net.URL, java.net.URL)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.JFreeReport parseReport(java.net.URL)
   * from tested class
   */
  public void testParseReport2050244018() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testParseReport2050244018(java.net.URL)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.JFreeReport parseReport(java.lang.String)
   * from tested class
   */
  public void testParseReport1195259493() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testParseReport1195259493(java.lang.String)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.JFreeReport parseReport(java.io.File)
   * from tested class
   */
  public void testParseReport2130072984() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testParseReport2130072984(java.io.File)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.JFreeReport parseReport(org.xml.sax.InputSource, java.net.URL)
   * from tested class
   */
  public void testParseReport5305009922050244018() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testParseReport5305009922050244018(org.xml.sax.InputSource, java.net.URL)

  /**
   * Method for testing how works original method:
   * void setDTDLocation(java.lang.String)
   * from tested class
   */
  public void testSetDTDLocation1195259493() {

    varReportGenerator.setDTDLocation((String)null);
    assertEquals((String)null, varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"");
    assertEquals((String)"", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\u0000");
    assertEquals((String)"\u0000", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)" ");
    assertEquals((String)" ", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\n");
    assertEquals((String)"\n", varReportGenerator.getDTDLocation());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varReportGenerator.setDTDLocation((String)null);
    assertEquals((String)null, varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"");
    assertEquals((String)"", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\u0000");
    assertEquals((String)"\u0000", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)" ");
    assertEquals((String)" ", varReportGenerator.getDTDLocation());
    varReportGenerator.setDTDLocation((String)"\n");
    assertEquals((String)"\n", varReportGenerator.getDTDLocation());

  } // end of testSetDTDLocation1195259493(java.lang.String)

  /**
   * Method for testing how works original method:
   * void setDefaultHandler( ... )
   * from tested class
   */
  public void testSetDefaultHandler2048962870() {

    varReportGenerator.setDefaultHandler((com.jrefinery.report.io.AbstractReportDefinitionHandler)null);
    assertEquals((com.jrefinery.report.io.AbstractReportDefinitionHandler)null, varReportGenerator.getDefaultHandler());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varReportGenerator.setDefaultHandler((com.jrefinery.report.io.AbstractReportDefinitionHandler)null);
    assertEquals((com.jrefinery.report.io.AbstractReportDefinitionHandler)null, varReportGenerator.getDefaultHandler());

  } // end of testSetDefaultHandler2048962870( ... )

} // end of ReportGeneratorTestCase
