/**
 * ================================================
 * LibLoader : a free Java resource loading library
 * ================================================
 *
 * Project Info:  http://www.jfree.org/jfreereport/libloader/
 * Project Lead:  Thomas Morgner;
 *
 * (C) Copyright 2006, by Pentaho Corporation and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * [Java is a trademark or registered trademark of Sun Microsystems, Inc.
 * in the United States and other countries.]
 *
 * ------------
 * RawResourceKey.java
 * ------------
 * (C) Copyright 2006, by Pentaho Corporation.
 *
 * Original Author:  Thomas Morgner;
 * Contributor(s):   -;
 *
 * $Id$
 *
 * Changes
 * -------
 *
 *
 */
package org.jfree.resourceloader.loader.raw;

import java.util.Arrays;

import org.jfree.resourceloader.ResourceKey;

/**
 * This is a resource key, which already caries all the data as byte[]. It is
 * intended to utilize the caching framework for other inline parsing (and its
 * main purpose is for caching style declarations for libLayout).
 *
 * @author Thomas Morgner
 */
public class RawResourceKey implements ResourceKey
{
  private byte[] data;

  public RawResourceKey(final byte[] data)
  {
    if (data == null)
    {
      throw new NullPointerException();
    }
    this.data = data;
  }

  /**
   * Returns the schema of this resource key. The schema can be mapped to a
   * known resource loader. If no resource loader is available for the given
   * schema, the resource will be unavailable.
   *
   * @return
   */
  public String getSchema()
  {
    return "raw:bytes";
  }

  public byte[] getData()
  {
    return (byte[]) data.clone();
  }

  public boolean equals(final Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (o == null || getClass() != o.getClass())
    {
      return false;
    }

    final RawResourceKey that = (RawResourceKey) o;
    return Arrays.equals(data, that.data);
  }

  public int hashCode()
  {
    return hashCode(data);
  }

  public static int hashCode(byte a[])
  {
    if (a == null)
    {
      return 0;
    }

    int result = 1;
    for (int i = 0; i < a.length; i++)
    {
      byte element = a[i];
      result = 29 * result + element;
    }
    return result;
  }

  /**
   * Creates a unique identifier for this key.
   * <p/>
   * The following statement must be true for all external forms generated by
   * this method: (key1.equals(key2) == key1.toExternalForm().equals(key2.toExternalForm())
   *
   * @return
   */
  public String toExternalForm()
  {
    final StringBuffer b = new StringBuffer ();
    b.append(data.length);
    b.append(":");
    for (int i = 0; i < data.length; i += 2)
    {
      char element = (char) (data[i] & 0xff);
      if (i + 1 < data.length)
      {
        element += (char) ((data[i] & 0xff) << 8);
      }
      b.append(element);
    }
    return b.toString();
  }
}
