/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id:$
 * $Author:$
 * $Date:$
 */
package com.jrefinery.report.ext.junit.base;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.JFreeReport;

/**
 * File <code>JFreeReportTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.JFreeReportTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class JFreeReportTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected JFreeReport varJFreeReport;

  /**
   * Public constructor for creating testing class.
   */
  public JFreeReportTestCase(String name) {
    super(name);
  } // end of JFreeReportTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
        public void eventDispatched(AWTEvent event) {
          WindowEvent we = ((WindowEvent) event);
          if (we.getID() == WindowEvent.WINDOW_OPENED)
            we.getWindow().dispose();
        }
      }, AWTEvent.WINDOW_EVENT_MASK);
    varJFreeReport = new JFreeReport();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(JFreeReportTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * void addFunction(com.jrefinery.report.function.Function)
   * from tested class
   */
  public void testAddFunction555184817() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAddFunction555184817(com.jrefinery.report.function.Function)

  /**
   * Method for testing how works original method:
   * void addGroup(com.jrefinery.report.Group)
   * from tested class
   */
  public void testAddGroup412552258() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testAddGroup412552258(com.jrefinery.report.Group)

  /**
   * Method for testing how works original method:
   * javax.swing.table.TableModel getData()
   * from tested class
   */
  public void testGetData() {

    varJFreeReport.setData((javax.swing.table.TableModel)null);
    assertEquals((javax.swing.table.TableModel)null, varJFreeReport.getData());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setData((javax.swing.table.TableModel)null);
    assertEquals((javax.swing.table.TableModel)null, varJFreeReport.getData());

  } // end of testGetData()

  /**
   * Method for testing how works original method:
   * java.awt.print.PageFormat getDefaultPageFormat()
   * from tested class
   */
  public void testGetDefaultPageFormat() {

    varJFreeReport.setDefaultPageFormat((java.awt.print.PageFormat)null);
    assertEquals((java.awt.print.PageFormat)null, varJFreeReport.getDefaultPageFormat());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setDefaultPageFormat((java.awt.print.PageFormat)null);
    assertEquals((java.awt.print.PageFormat)null, varJFreeReport.getDefaultPageFormat());

  } // end of testGetDefaultPageFormat()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.FunctionCollection getFunctions()
   * from tested class
   */
  public void testGetFunctions() {

    varJFreeReport.setFunctions((com.jrefinery.report.FunctionCollection)null);
    assertEquals((com.jrefinery.report.FunctionCollection)null, varJFreeReport.getFunctions());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setFunctions((com.jrefinery.report.FunctionCollection)null);
    assertEquals((com.jrefinery.report.FunctionCollection)null, varJFreeReport.getFunctions());

  } // end of testGetFunctions()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.Group getGroup(int)
   * from tested class
   */
  public void testGetGroup104431() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetGroup104431(int)

  /**
   * Method for testing how works original method:
   * int getGroupCount()
   * from tested class
   */
  public void testGetGroupCount() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetGroupCount()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.GroupList getGroups()
   * from tested class
   */
  public void testGetGroups() {

    varJFreeReport.setGroups((com.jrefinery.report.GroupList)null);
    assertEquals((com.jrefinery.report.GroupList)null, varJFreeReport.getGroups());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setGroups((com.jrefinery.report.GroupList)null);
    assertEquals((com.jrefinery.report.GroupList)null, varJFreeReport.getGroups());

  } // end of testGetGroups()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ItemBand getItemBand()
   * from tested class
   */
  public void testGetItemBand() {

    varJFreeReport.setItemBand((com.jrefinery.report.ItemBand)null);
    assertEquals((com.jrefinery.report.ItemBand)null, varJFreeReport.getItemBand());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setItemBand((com.jrefinery.report.ItemBand)null);
    assertEquals((com.jrefinery.report.ItemBand)null, varJFreeReport.getItemBand());

  } // end of testGetItemBand()

  /**
   * Method for testing how works original method:
   * java.lang.String getName()
   * from tested class
   */
  public void testGetName() {

    varJFreeReport.setName((String)null);
    assertEquals((String)null, varJFreeReport.getName());
    varJFreeReport.setName((String)"");
    assertEquals((String)"", varJFreeReport.getName());
    varJFreeReport.setName((String)"\u0000");
    assertEquals((String)"\u0000", varJFreeReport.getName());
    varJFreeReport.setName((String)" ");
    assertEquals((String)" ", varJFreeReport.getName());
    varJFreeReport.setName((String)"\n");
    assertEquals((String)"\n", varJFreeReport.getName());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setName((String)null);
    assertEquals((String)null, varJFreeReport.getName());
    varJFreeReport.setName((String)"");
    assertEquals((String)"", varJFreeReport.getName());
    varJFreeReport.setName((String)"\u0000");
    assertEquals((String)"\u0000", varJFreeReport.getName());
    varJFreeReport.setName((String)" ");
    assertEquals((String)" ", varJFreeReport.getName());
    varJFreeReport.setName((String)"\n");
    assertEquals((String)"\n", varJFreeReport.getName());

  } // end of testGetName()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.PageFooter getPageFooter()
   * from tested class
   */
  public void testGetPageFooter() {

    varJFreeReport.setPageFooter((com.jrefinery.report.PageFooter)null);
    assertEquals((com.jrefinery.report.PageFooter)null, varJFreeReport.getPageFooter());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setPageFooter((com.jrefinery.report.PageFooter)null);
    assertEquals((com.jrefinery.report.PageFooter)null, varJFreeReport.getPageFooter());

  } // end of testGetPageFooter()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.PageHeader getPageHeader()
   * from tested class
   */
  public void testGetPageHeader() {

    varJFreeReport.setPageHeader((com.jrefinery.report.PageHeader)null);
    assertEquals((com.jrefinery.report.PageHeader)null, varJFreeReport.getPageHeader());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setPageHeader((com.jrefinery.report.PageHeader)null);
    assertEquals((com.jrefinery.report.PageHeader)null, varJFreeReport.getPageHeader());

  } // end of testGetPageHeader()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.util.ReportProperties getProperties()
   * from tested class
   */
  public void testGetProperties() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testGetProperties()

  /**
   * Method for testing how works original method:
   * java.lang.Object getProperty(java.lang.String)
   * from tested class
   */
  public void testGetProperty1195259493() {

    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

    assertTrue("Warning! This new test method with no real test code inside.", false);
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.


  } // end of testGetProperty1195259493(java.lang.String)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportFooter getReportFooter()
   * from tested class
   */
  public void testGetReportFooter() {

    varJFreeReport.setReportFooter((com.jrefinery.report.ReportFooter)null);
    assertEquals((com.jrefinery.report.ReportFooter)null, varJFreeReport.getReportFooter());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setReportFooter((com.jrefinery.report.ReportFooter)null);
    assertEquals((com.jrefinery.report.ReportFooter)null, varJFreeReport.getReportFooter());

  } // end of testGetReportFooter()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportHeader getReportHeader()
   * from tested class
   */
  public void testGetReportHeader() {

    varJFreeReport.setReportHeader((com.jrefinery.report.ReportHeader)null);
    assertEquals((com.jrefinery.report.ReportHeader)null, varJFreeReport.getReportHeader());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setReportHeader((com.jrefinery.report.ReportHeader)null);
    assertEquals((com.jrefinery.report.ReportHeader)null, varJFreeReport.getReportHeader());

  } // end of testGetReportHeader()

  /**
   * Method for testing how works original method:
   * boolean isLastItemInHigherGroups(int, int)
   * from tested class
   */
  public void testIsLastItemInHigherGroups104431104431() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIsLastItemInHigherGroups104431104431(int, int)

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportState processPage( ... )
   * from tested class
   */
  public void testProcessPage32060089178708140864711720() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testProcessPage32060089178708140864711720( ... )

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportState processReport( ... )
   * from tested class
   */
  public void testProcessReport320600891() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testProcessReport320600891( ... )

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportStateList repaginate( ... )
   * from tested class
   */
  public void testRepaginate320600891787081408() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testRepaginate320600891787081408( ... )

  /**
   * Method for testing how works original method:
   * void setData(javax.swing.table.TableModel)
   * from tested class
   */
  public void testSetData1377573251() {

    varJFreeReport.setData((javax.swing.table.TableModel)null);
    assertEquals((javax.swing.table.TableModel)null, varJFreeReport.getData());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setData((javax.swing.table.TableModel)null);
    assertEquals((javax.swing.table.TableModel)null, varJFreeReport.getData());

  } // end of testSetData1377573251(javax.swing.table.TableModel)

  /**
   * Method for testing how works original method:
   * void setDefaultPageFormat(java.awt.print.PageFormat)
   * from tested class
   */
  public void testSetDefaultPageFormat1429744291() {

    varJFreeReport.setDefaultPageFormat((java.awt.print.PageFormat)null);
    assertEquals((java.awt.print.PageFormat)null, varJFreeReport.getDefaultPageFormat());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setDefaultPageFormat((java.awt.print.PageFormat)null);
    assertEquals((java.awt.print.PageFormat)null, varJFreeReport.getDefaultPageFormat());

  } // end of testSetDefaultPageFormat1429744291(java.awt.print.PageFormat)

  /**
   * Method for testing how works original method:
   * void setFunctions(com.jrefinery.report.FunctionCollection)
   * from tested class
   */
  public void testSetFunctions710848435() {

    varJFreeReport.setFunctions((com.jrefinery.report.FunctionCollection)null);
    assertEquals((com.jrefinery.report.FunctionCollection)null, varJFreeReport.getFunctions());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setFunctions((com.jrefinery.report.FunctionCollection)null);
    assertEquals((com.jrefinery.report.FunctionCollection)null, varJFreeReport.getFunctions());

  } // end of testSetFunctions710848435(com.jrefinery.report.FunctionCollection)

  /**
   * Method for testing how works original method:
   * void setGroups(com.jrefinery.report.GroupList)
   * from tested class
   */
  public void testSetGroups1577631744() {

    varJFreeReport.setGroups((com.jrefinery.report.GroupList)null);
    assertEquals((com.jrefinery.report.GroupList)null, varJFreeReport.getGroups());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setGroups((com.jrefinery.report.GroupList)null);
    assertEquals((com.jrefinery.report.GroupList)null, varJFreeReport.getGroups());

  } // end of testSetGroups1577631744(com.jrefinery.report.GroupList)

  /**
   * Method for testing how works original method:
   * void setItemBand(com.jrefinery.report.ItemBand)
   * from tested class
   */
  public void testSetItemBand1181375675() {

    varJFreeReport.setItemBand((com.jrefinery.report.ItemBand)null);
    assertEquals((com.jrefinery.report.ItemBand)null, varJFreeReport.getItemBand());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setItemBand((com.jrefinery.report.ItemBand)null);
    assertEquals((com.jrefinery.report.ItemBand)null, varJFreeReport.getItemBand());

  } // end of testSetItemBand1181375675(com.jrefinery.report.ItemBand)

  /**
   * Method for testing how works original method:
   * void setName(java.lang.String)
   * from tested class
   */
  public void testSetName1195259493() {

    varJFreeReport.setName((String)null);
    assertEquals((String)null, varJFreeReport.getName());
    varJFreeReport.setName((String)"");
    assertEquals((String)"", varJFreeReport.getName());
    varJFreeReport.setName((String)"\u0000");
    assertEquals((String)"\u0000", varJFreeReport.getName());
    varJFreeReport.setName((String)" ");
    assertEquals((String)" ", varJFreeReport.getName());
    varJFreeReport.setName((String)"\n");
    assertEquals((String)"\n", varJFreeReport.getName());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setName((String)null);
    assertEquals((String)null, varJFreeReport.getName());
    varJFreeReport.setName((String)"");
    assertEquals((String)"", varJFreeReport.getName());
    varJFreeReport.setName((String)"\u0000");
    assertEquals((String)"\u0000", varJFreeReport.getName());
    varJFreeReport.setName((String)" ");
    assertEquals((String)" ", varJFreeReport.getName());
    varJFreeReport.setName((String)"\n");
    assertEquals((String)"\n", varJFreeReport.getName());

  } // end of testSetName1195259493(java.lang.String)

  /**
   * Method for testing how works original method:
   * void setPageFooter(com.jrefinery.report.PageFooter)
   * from tested class
   */
  public void testSetPageFooter2016302809() {

    varJFreeReport.setPageFooter((com.jrefinery.report.PageFooter)null);
    assertEquals((com.jrefinery.report.PageFooter)null, varJFreeReport.getPageFooter());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setPageFooter((com.jrefinery.report.PageFooter)null);
    assertEquals((com.jrefinery.report.PageFooter)null, varJFreeReport.getPageFooter());

  } // end of testSetPageFooter2016302809(com.jrefinery.report.PageFooter)

  /**
   * Method for testing how works original method:
   * void setPageHeader(com.jrefinery.report.PageHeader)
   * from tested class
   */
  public void testSetPageHeader1968712167() {

    varJFreeReport.setPageHeader((com.jrefinery.report.PageHeader)null);
    assertEquals((com.jrefinery.report.PageHeader)null, varJFreeReport.getPageHeader());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setPageHeader((com.jrefinery.report.PageHeader)null);
    assertEquals((com.jrefinery.report.PageHeader)null, varJFreeReport.getPageHeader());

  } // end of testSetPageHeader1968712167(com.jrefinery.report.PageHeader)

  /**
   * Method for testing how works original method:
   * void setProperty(java.lang.String, java.lang.Object)
   * from tested class
   */
  public void testSetProperty11952594931063877011() {

    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.

    assertTrue("Warning! This new test method with no real test code inside.", false);
    // Warning in get/set methods pair 'set' method should have only one
    // parameter. The same type which is returned by corresponding get method.


  } // end of testSetProperty11952594931063877011(java.lang.String, java.lang.Object)

  /**
   * Method for testing how works original method:
   * void setReportFooter(com.jrefinery.report.ReportFooter)
   * from tested class
   */
  public void testSetReportFooter993900748() {

    varJFreeReport.setReportFooter((com.jrefinery.report.ReportFooter)null);
    assertEquals((com.jrefinery.report.ReportFooter)null, varJFreeReport.getReportFooter());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setReportFooter((com.jrefinery.report.ReportFooter)null);
    assertEquals((com.jrefinery.report.ReportFooter)null, varJFreeReport.getReportFooter());

  } // end of testSetReportFooter993900748(com.jrefinery.report.ReportFooter)

  /**
   * Method for testing how works original method:
   * void setReportHeader(com.jrefinery.report.ReportHeader)
   * from tested class
   */
  public void testSetReportHeader1041491390() {

    varJFreeReport.setReportHeader((com.jrefinery.report.ReportHeader)null);
    assertEquals((com.jrefinery.report.ReportHeader)null, varJFreeReport.getReportHeader());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varJFreeReport.setReportHeader((com.jrefinery.report.ReportHeader)null);
    assertEquals((com.jrefinery.report.ReportHeader)null, varJFreeReport.getReportHeader());

  } // end of testSetReportHeader1041491390(com.jrefinery.report.ReportHeader)

} // end of JFreeReportTestCase
