/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id: RectangleShapeElementTestCase.java,v 1.1 2002/07/08 22:10:35 taqua Exp $
 * $Author: taqua $
 * $Date: 2002/07/08 22:10:35 $
 */
package com.jrefinery.report.ext.junit.base;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.Rectangle;
import java.awt.geom.Line2D;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.RectangleShapeElement;

/**
 * File <code>RectangleShapeElementTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.RectangleShapeElementTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class RectangleShapeElementTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected RectangleShapeElement varRectangleShapeElement;

  /**
   * Public constructor for creating testing class.
   */
  public RectangleShapeElementTestCase(String name) {
    super(name);
  } // end of RectangleShapeElementTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    varRectangleShapeElement = new RectangleShapeElement();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(RectangleShapeElementTestCase.class);
  } // end of suite()

  /**
   * Method for testing how works original method:
   * void setBounds(java.awt.geom.Rectangle2D)
   * from tested class
   */
  public void testSetBounds227781269() {

    try
    {
      varRectangleShapeElement.setBounds((java.awt.geom.Rectangle2D)null);
      assertTrue("Failed to throw a nullpointer", false);
    }
    catch (NullPointerException npe)
    {
    }
    Rectangle r = new Rectangle(1,1,2,2);
    varRectangleShapeElement = new RectangleShapeElement();
    varRectangleShapeElement.setBounds(r);
    assertEquals(r, varRectangleShapeElement.getBounds());

  } // end of testSetBounds227781269(java.awt.geom.Rectangle2D)

  /**
   * Method for testing how works original method:
   * void setRectangle(java.awt.geom.Rectangle2D)
   * from tested class
   */
  public void testSetRectangle227781269() {

    try
    {
      varRectangleShapeElement.setRectangle((java.awt.geom.Rectangle2D)null);
      assertTrue("Failed to throw a nullpointer", false);
    }
    catch (NullPointerException npe)
    {
    }
    Rectangle r = new Rectangle(1,1,2,2);
    varRectangleShapeElement = new RectangleShapeElement();
    varRectangleShapeElement.setRectangle(r);
    assertEquals(r, varRectangleShapeElement.getRectangle());

  } // end of testSetRectangle227781269(java.awt.geom.Rectangle2D)

  /**
   * Method for testing how works original method:
   * void setShape(java.awt.Shape)
   * from tested class
   */
  public void testSetShape2073736251() {

    try
    {
      varRectangleShapeElement.setShape(null);
      assertTrue("Failed to throw a nullpointer", false);
    }
    catch (NullPointerException npe)
    {
    }
    try
    {
      Line2D l = new Line2D.Float (1,1,1,1);
      varRectangleShapeElement = new RectangleShapeElement();
      varRectangleShapeElement.setShape(l);
      assertTrue("No expected classcast exception, failed", false);
    }
    catch (ClassCastException ce)
    {
    }

    Rectangle r = new Rectangle(1,1,2,2);
    varRectangleShapeElement = new RectangleShapeElement();
    varRectangleShapeElement.setShape(r);
    assertEquals(r, varRectangleShapeElement.getShape());
  } // end of testSetShape2073736251(java.awt.Shape)

} // end of RectangleShapeElementTestCase
