/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id: ReportStateListTestCase.java,v 1.1 2002/07/08 22:10:35 taqua Exp $
 * $Author: taqua $
 * $Date: 2002/07/08 22:10:35 $
 */
package com.jrefinery.report.ext.junit.base;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.print.PageFormat;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.ReportStateList;
import com.jrefinery.report.ReportState;
import com.jrefinery.report.JFreeReport;
import com.jrefinery.report.ReportProcessor;
import com.jrefinery.report.PageFooter;
import com.jrefinery.report.targets.OutputTarget;
import com.jrefinery.report.targets.G2OutputTarget;

/**
 * File <code>ReportStateListTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ReportStateListTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class ReportStateListTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected ReportStateList varReportStateList;
  protected JFreeReport report;
  protected G2OutputTarget output;

  /**
   * Public constructor for creating testing class.
   */
  public ReportStateListTestCase(String name) {
    super(name);
  } // end of ReportStateListTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    // Initialize your variable(s) here
    // for example:
    // varReportStateList = new ReportStateList(...);
    // But note that there is no default constructor in ReportStateList
    report = new JFreeReport();
    output = new G2OutputTarget (G2OutputTarget.createEmptyGraphics(), new PageFormat());
    varReportStateList = new ReportStateList(report, output);
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(ReportStateListTestCase.class);
  } // end of suite()

  /**
   * Method for testing how works original method:
   * void add(com.jrefinery.report.ReportState)
   * from tested class
   */
  public void testAdd787081408() {

    varReportStateList.clear();
    varReportStateList.add(new ReportState.Start(new JFreeReport()));
    try
    {
      varReportStateList.add(null);
      assertTrue("NullPointer not caught", false);
    }
    catch (NullPointerException npe)
    {
    }

  } // end of testAdd787081408(com.jrefinery.report.ReportState)

  /**
   * Method for testing how works original method:
   * void clear()
   * from tested class
   */
  public void testClear() {

    varReportStateList.add(new ReportState.Start (new JFreeReport()));
    assertTrue("Filled", varReportStateList.size() != 0);

    varReportStateList.clear();
    assertTrue("Empty", varReportStateList.size() == 0);

  } // end of testClear()

  /**
   * Method for testing how works original method:
   * com.jrefinery.report.ReportState get(int)
   * from tested class
   */
  public void testGet104431() {

    ReportState start = new ReportState.Start(new JFreeReport());
    ReportState next = start.advance(new ReportProcessor(output, false, new PageFooter()));
    varReportStateList.clear();
    varReportStateList.add(start);
    varReportStateList.add(next);

    assertEquals(varReportStateList.get(0), start);
    assertEquals(varReportStateList.get(1), next);
  } // end of testGet104431(int)

  /**
   * Method for testing how works original method:
   * int size()
   * from tested class
   */
  public void testSize() {
    varReportStateList.clear();
    varReportStateList.add(new ReportState.Start(new JFreeReport()));
    try
    {
      varReportStateList.add(null);
      assertTrue("NullPointer not caught", false);
    }
    catch (NullPointerException npe)
    {
    }
    assertTrue("SizeTest", varReportStateList.size() == 1);

  } // end of testSize()

} // end of ReportStateListTestCase
