/**
 * =========================================
 * LibFormula : a free Java formula library
 * =========================================
 *
 * Project Info:  http://reporting.pentaho.org/libformula/
 *
 * (C) Copyright 2006-2007, by Pentaho Corporation and Contributors.
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 * [Java is a trademark or registered trademark of Sun Microsystems, Inc.
 * in the United States and other countries.]
 *
 *
 * ------------
 * $Id: FormulaParser.java,v 1.8 2007/06/10 13:35:47 taqua Exp $
 * ------------
 * (C) Copyright 2006-2007, by Pentaho Corporation.
 */
/* Generated By:JavaCC: Do not edit this line. GeneratedFormulaParserConstants.java */
package org.jfree.formula.parser;

public interface GeneratedFormulaParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int LETTER = 3;
  int NON_ZERO_DIGIT = 4;
  int DIGIT = 5;
  int HEX_DIGIT = 6;
  int BINARY_DIGIT = 7;
  int UNSIGNED_INTEGER = 8;
  int EXPONENT_PART = 9;
  int NEWLINE = 10;
  int NONQUOTE_CHARACTER = 11;
  int NONQUOTE_LOOKUP = 12;
  int COMMA = 13;
  int PERIOD = 14;
  int COLON = 15;
  int QUOTE = 16;
  int DQUOTE = 17;
  int SEMICOLON = 18;
  int L_PAREN = 19;
  int R_PAREN = 20;
  int L_BRACKET = 21;
  int R_BRACKET = 22;
  int QUEST = 23;
  int L_BRACE = 24;
  int R_BRACE = 25;
  int PIPE = 26;
  int PLUS = 27;
  int MINUS = 28;
  int MULT = 29;
  int DIV = 30;
  int POW = 31;
  int EQUALS = 32;
  int NOT_EQUALS = 33;
  int LT_EQUALS = 34;
  int GT_EQUALS = 35;
  int LT = 36;
  int GT = 37;
  int CONCAT = 38;
  int PERCENT = 39;
  int IDENTIFIER = 40;
  int COLUMN_LOOKUP = 41;
  int STRING_LITERAL = 42;
  int UNSIGNED_NUMERIC_LITERAL = 43;
  int EXACT_NUMERIC_LITERAL = 44;
  int APPROXIMATE_NUMERIC_LITERAL = 45;
  int MANTISSA = 46;
  int SIGN = 47;
  int NULL = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "<LETTER>",
    "<NON_ZERO_DIGIT>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "<BINARY_DIGIT>",
    "<UNSIGNED_INTEGER>",
    "<EXPONENT_PART>",
    "<NEWLINE>",
    "<NONQUOTE_CHARACTER>",
    "<NONQUOTE_LOOKUP>",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"%\"",
    "<IDENTIFIER>",
    "<COLUMN_LOOKUP>",
    "<STRING_LITERAL>",
    "<UNSIGNED_NUMERIC_LITERAL>",
    "<EXACT_NUMERIC_LITERAL>",
    "<APPROXIMATE_NUMERIC_LITERAL>",
    "<MANTISSA>",
    "<SIGN>",
    "\"null\"",
  };

}
