/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id:$
 * $Author:$
 * $Date:$
 */
package com.jrefinery.report.ext.junit.base.filter;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.filter.NumberFormatFilter;

/**
 * File <code>NumberFormatFilterTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.filter.NumberFormatFilterTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class NumberFormatFilterTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected NumberFormatFilter varNumberFormatFilter;

  /**
   * Public constructor for creating testing class.
   */
  public NumberFormatFilterTestCase(String name) {
    super(name);
  } // end of NumberFormatFilterTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
        public void eventDispatched(AWTEvent event) {
          WindowEvent we = ((WindowEvent) event);
          if (we.getID() == WindowEvent.WINDOW_OPENED)
            we.getWindow().dispose();
        }
      }, AWTEvent.WINDOW_EVENT_MASK);
    varNumberFormatFilter = new NumberFormatFilter();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(NumberFormatFilterTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * int getMaximumFractionDigits()
   * from tested class
   */
  public void testGetMaximumFractionDigits() {

    varNumberFormatFilter.setMaximumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumFractionDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMaximumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumFractionDigits());

  } // end of testGetMaximumFractionDigits()

  /**
   * Method for testing how works original method:
   * int getMaximumIntegerDigits()
   * from tested class
   */
  public void testGetMaximumIntegerDigits() {

    varNumberFormatFilter.setMaximumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumIntegerDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMaximumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumIntegerDigits());

  } // end of testGetMaximumIntegerDigits()

  /**
   * Method for testing how works original method:
   * int getMinimumFractionDigits()
   * from tested class
   */
  public void testGetMinimumFractionDigits() {

    varNumberFormatFilter.setMinimumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumFractionDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMinimumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumFractionDigits());

  } // end of testGetMinimumFractionDigits()

  /**
   * Method for testing how works original method:
   * int getMinimumIntegerDigits()
   * from tested class
   */
  public void testGetMinimumIntegerDigits() {

    varNumberFormatFilter.setMinimumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumIntegerDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMinimumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumIntegerDigits());

  } // end of testGetMinimumIntegerDigits()

  /**
   * Method for testing how works original method:
   * java.text.NumberFormat getNumberFormat()
   * from tested class
   */
  public void testGetNumberFormat() {

    varNumberFormatFilter.setNumberFormat((java.text.NumberFormat)null);
    assertEquals((java.text.NumberFormat)null, varNumberFormatFilter.getNumberFormat());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setNumberFormat((java.text.NumberFormat)null);
    assertEquals((java.text.NumberFormat)null, varNumberFormatFilter.getNumberFormat());

  } // end of testGetNumberFormat()

  /**
   * Method for testing how works original method:
   * boolean isGroupingUsed()
   * from tested class
   */
  public void testIsGroupingUsed() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testIsGroupingUsed()

  /**
   * Method for testing how works original method:
   * void setFormatter(java.text.Format)
   * from tested class
   */
  public void testSetFormatter1171274196() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSetFormatter1171274196(java.text.Format)

  /**
   * Method for testing how works original method:
   * void setGroupingUsed(boolean)
   * from tested class
   */
  public void testSetGroupingUsed64711720() {

    assertTrue("Warning! This new test method with no real test code inside.", false);

  } // end of testSetGroupingUsed64711720(boolean)

  /**
   * Method for testing how works original method:
   * void setMaximumFractionDigits(int)
   * from tested class
   */
  public void testSetMaximumFractionDigits104431() {

    varNumberFormatFilter.setMaximumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumFractionDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMaximumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumFractionDigits());
    varNumberFormatFilter.setMaximumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumFractionDigits());

  } // end of testSetMaximumFractionDigits104431(int)

  /**
   * Method for testing how works original method:
   * void setMaximumIntegerDigits(int)
   * from tested class
   */
  public void testSetMaximumIntegerDigits104431() {

    varNumberFormatFilter.setMaximumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumIntegerDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMaximumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMaximumIntegerDigits());
    varNumberFormatFilter.setMaximumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMaximumIntegerDigits());

  } // end of testSetMaximumIntegerDigits104431(int)

  /**
   * Method for testing how works original method:
   * void setMinimumFractionDigits(int)
   * from tested class
   */
  public void testSetMinimumFractionDigits104431() {

    varNumberFormatFilter.setMinimumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumFractionDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMinimumFractionDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumFractionDigits());
    varNumberFormatFilter.setMinimumFractionDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumFractionDigits());

  } // end of testSetMinimumFractionDigits104431(int)

  /**
   * Method for testing how works original method:
   * void setMinimumIntegerDigits(int)
   * from tested class
   */
  public void testSetMinimumIntegerDigits104431() {

    varNumberFormatFilter.setMinimumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumIntegerDigits());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setMinimumIntegerDigits((int)-2147483648);
    assertEquals((int)-2147483648, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)-1);
    assertEquals((int)-1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)0);
    assertEquals((int)0, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)1);
    assertEquals((int)1, varNumberFormatFilter.getMinimumIntegerDigits());
    varNumberFormatFilter.setMinimumIntegerDigits((int)2147483647);
    assertEquals((int)2147483647, varNumberFormatFilter.getMinimumIntegerDigits());

  } // end of testSetMinimumIntegerDigits104431(int)

  /**
   * Method for testing how works original method:
   * void setNumberFormat(java.text.NumberFormat)
   * from tested class
   */
  public void testSetNumberFormat1906575595() {

    varNumberFormatFilter.setNumberFormat((java.text.NumberFormat)null);
    assertEquals((java.text.NumberFormat)null, varNumberFormatFilter.getNumberFormat());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varNumberFormatFilter.setNumberFormat((java.text.NumberFormat)null);
    assertEquals((java.text.NumberFormat)null, varNumberFormatFilter.getNumberFormat());

  } // end of testSetNumberFormat1906575595(java.text.NumberFormat)

} // end of NumberFormatFilterTestCase
