/*
 * File is generated by 'Unit Tests Generator' developed under
 * 'Web Test Tools' project at http://sf.net/projects/wttools/
 * Copyright (C) 2001 "Artur Hefczyc" <kobit@users.sourceforge.net>
 * to all 'Web Test Tools' subprojects.
 *
 * No rigths to files and no responsibility for code generated
 * by this tool are belonged to author of 'unittestsgen' utility.
 *
 * $Id: BandCursorTestCase.java,v 1.1 2002/07/08 22:10:38 taqua Exp $
 * $Author: taqua $
 * $Date: 2002/07/08 22:10:38 $
 */
package com.jrefinery.report.ext.junit.base.targets;

import junit.framework.*;
import junit.extensions.*;
import java.awt.Toolkit;
import java.awt.AWTEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.WindowEvent;

import com.jrefinery.report.targets.BandCursor;

/**
 * File <code>BandCursorTestCase.java</code> is automaticaly generated by
 * 'unittestsgen' application. Code generator is created for java
 * sources and for 'junit' package by "Artur Hefczyc"
 * <kobit@users.sourceforge.net><br/>
 * You should fulfil test methods with proper code for testing
 * purpose. All methods where you should put your code are below and
 * their names starts with 'test'.<br/>
 * You can run unit tests in many ways, however prefered are:
 * <ul>
 *   <li>Run tests for one class only, for example for this class you
 *       can run tests with command:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.targets.BandCursorTestCase
 *     </pre>
 *   </li>
 *   <li>Run tests for all classes in one command call. Code generator
 *       creates also <code>com.jrefinery.report.ext.junit.TestAll.class</code> which runs all
 *       available tests:
 *     <pre>
 *       java -cp "jar/thisjarfile.jar;lib/junit.jar" com.jrefinery.report.ext.junit.TestAll
 *     </pre>
 *   </li>
 *   <li>But the most prefered way is to run all tests from
 *     <em>Ant</em> just after compilation process finished.<br/>
 *     To do it. You need:
 *     <ol>
 *       <li>Ant package from
 *         <a href="http://jakarta.apache.org/">Ant</a>
 *       </li>
 *       <li>JUnit package from
 *         <a href="http://www.junit.org/">JUnit</a>
 *       </li>
 *       <li>Put some code in your <code>build.xml</code> file
 *         to tell Ant how to test your package. Sample code for
 *         Ant's <code>build.xml</code> you can find in created file:
 *         <code>sample-junit-build.xml</code>. And remember to have
 *         <code>junit.jar</code> in CLASSPATH <b>before</b> you run Ant.
 *         To generate reports by ant you must have <code>xalan.jar</code>
 *         in your <code>ANT_HOME/lib/</code> directory.
 *       </li>
 *     </ol>
 *   </li>
 * </ul>
 */
public class BandCursorTestCase extends TestCase
{
  /**
   * Instance of tested class.
   */
  protected BandCursor varBandCursor;

  /**
   * Public constructor for creating testing class.
   */
  public BandCursorTestCase(String name) {
    super(name);
  } // end of BandCursorTestCase(String name)
  /**
   * This main method is used for run tests for this class only
   * from command line.
   */
  public static void main(String[] args) {
    junit.textui.TestRunner.run(suite());
  } // end of main(Stringp[] args)
  /**
   * This method is called every time before particular test execution.
   * It creates new instance of tested class and it can perform some more
   * actions which are necessary for performs tests.
   */
  protected void setUp() {
    varBandCursor = new BandCursor();
  } // end of setUp()
  /**
   * Returns all tests which should be performed for testing class.
   * By default it returns only name of testing class. Instance of this
   * is then created with its constructor.
   */
  public static Test suite() {
    return new TestSuite(BandCursorTestCase.class);
  } // end of suite()
  /**
   * for classes which doesn't contain any methods here is one additional
   * method for performing test on such classes.
   */
  public void testNoMethods() {
  }

  /**
   * Method for testing how works original method:
   * java.awt.geom.Rectangle2D getBandBounds()
   * from tested class
   */
  public void testGetBandBounds() {

    varBandCursor.setBandBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getBandBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setBandBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getBandBounds());

  } // end of testGetBandBounds()

  /**
   * Method for testing how works original method:
   * java.awt.geom.Rectangle2D getDrawBounds()
   * from tested class
   */
  public void testGetDrawBounds() {

    varBandCursor.setDrawBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getDrawBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setDrawBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getDrawBounds());

  } // end of testGetDrawBounds()

  /**
   * Method for testing how works original method:
   * java.awt.geom.Rectangle2D getElementBounds()
   * from tested class
   */
  public void testGetElementBounds() {

    varBandCursor.setElementBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getElementBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setElementBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getElementBounds());

  } // end of testGetElementBounds()

  /**
   * Method for testing how works original method:
   * void setBandBounds(java.awt.geom.Rectangle2D)
   * from tested class
   */
  public void testSetBandBounds227781269() {

    varBandCursor.setBandBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getBandBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setBandBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getBandBounds());

  } // end of testSetBandBounds227781269(java.awt.geom.Rectangle2D)

  /**
   * Method for testing how works original method:
   * void setDrawBounds(java.awt.geom.Rectangle2D)
   * from tested class
   */
  public void testSetDrawBounds227781269() {

    varBandCursor.setDrawBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getDrawBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setDrawBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getDrawBounds());

  } // end of testSetDrawBounds227781269(java.awt.geom.Rectangle2D)

  /**
   * Method for testing how works original method:
   * void setElementBounds(java.awt.geom.Rectangle2D)
   * from tested class
   */
  public void testSetElementBounds227781269() {

    varBandCursor.setElementBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getElementBounds());
    assertTrue("Warning! This new test method with no real test code inside.", false);
    varBandCursor.setElementBounds((java.awt.geom.Rectangle2D)null);
    assertEquals((java.awt.geom.Rectangle2D)null, varBandCursor.getElementBounds());

  } // end of testSetElementBounds227781269(java.awt.geom.Rectangle2D)

} // end of BandCursorTestCase
